services:
  mongodb-service:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  nodeapi-service:
    image: node:24-alpine
    container_name: noteapi
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8002:8002"
    depends_on:
      - mongodb-service
    command: sh -c "npm install && node index.js"
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongodb_data: